services:
  # the name of the api container
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
  # the name of the client container
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"
