FROM node:16-alpine as build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json yarn.lock ./

COPY ./src ./src
COPY ./public ./public

RUN yarn install 
RUN yarn build


FROM httpd:2.4
COPY --from=build-step /app/build/ /usr/local/apache2/htdocs